#!/usr/bin/python3.7
from subprocess import Popen
import sys
import time
import logging

logging.basicConfig(filename='app.log', filemode='w', format='%(name)s - %(levelname)s - %(message)s')

filename = sys.argv[1]
while True:
	logging.error(time.ctime(time.time()) + ": App crashed. restarting...")
	p = Popen("python " + filename, shell=True)
	p.wait()
